trigger:
  branches:
    include:
      - dev
      - uat

variables:
  tag: '$(Build.BuildId)'
  appName: 'kafka-notification-worker'
  apiName: 'NotificationWorker'
  namespace: 'default'
  dockerfilePath: 'Dockerfile'
  devEnv: 'dev'
  uatEnv: 'uat'
  acrRegistry: 'tokiacr'
  acrLoginServer: 'tokiacr.azurecr.io'
  acrUsername: 'tokiacr'
  imageNameDev: 'tokiacr-kafka-notification-worker-dev'
  imageNameUat: 'tokiacr-kafka-notification-worker-uat'
  imageVersion: latest
  vmImageName: 'ubuntu-latest'
  buildConfiguration: 'Release'

stages:
- stage: BuildDEV
  condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/dev'))
  displayName: DEV
  jobs:
    - job: Build
      displayName: Build and Push to ACR
      pool:
        vmImage: $(vmImageName)
      steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              docker login -u $(acrUsername) -p $(acrPasswordDev) $(acrLoginServer)
              docker build --build-arg environment=Development -t $(acrLoginServer)/$(devEnv)/$(imageNameDev):$(tag) $(Build.SourcesDirectory)
              docker push $(acrLoginServer)/$(devEnv)/$(imageNameDev):$(tag)

- stage: BuildUAT
  condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/uat'))
  displayName: UAT
  jobs:
    - job: Build
      displayName: Build and Push to ACR
      pool:
        vmImage: $(vmImageName)
      steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              docker login -u $(acrUsername) -p $(acrPasswordUat) $(acrLoginServer)
              docker build --build-arg environment=uat -t $(acrLoginServer)/$(uatEnv)/$(imageNameUat):$(tag) $(Build.SourcesDirectory)
              docker push $(acrLoginServer)/$(uatEnv)/$(imageNameUat):$(tag)